name: PR Review

on:
  pull_request:
    branches: [master]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check for template
        run: |
          # Read the content of the template file
          TEMPLATE_CONTENT=$(cat .github/PULL_REQUEST_TEMPLATE.md)

          # Check if the template exists in the PR body
          if [[ "${{ github.event.pull_request.body }}" =~ "$TEMPLATE_CONTENT" ]]; then
            echo "Template found!"
          else
            echo "Error: PR template is missing!"
            exit 1
          fi

      - name: Set draft status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            console.log(context.issue);
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'draft'
            })

      - name: Add bot-review label
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['bot-review']
            })

      - name: Remove bot-review label
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'bot-review'
            })
